### ISSUE TITLE
WNT pathway

### ISSUE THREAD

**Issue by imkeller** [saezlab/progeny#10]
I am trying to calculate the pathway scores for WNT signaling, but all I can get are these pathways:  
[1] "EGFR"     "Hypoxia"  "JAK.STAT" "MAPK"  "NFkB"   "PI3K"     "TGFb"     "TNFa"     "Trail"    "VEGF"   "p53" .

On the website it says : "We expanded human and mouse PROGENy with the pathways Androgen, Estrogen and WNT." 

How do I get these new pathways?

Thanks, Katharina

**Comment by christianholland** [comment]
Dear Katharina,

thanks for using PROGENy. Indeed we have expanded the collection of pathways with Androgen, Estrogen and WNT. 
You have basically two options how you can access these pathway:
i) We are currently updating the [PROGENy bioconductor package ](https://bioconductor.org/packages/release/bioc/html/progeny.html). You can install the **development** version via `devtools::install_github("saezlab/progeny", ref = "bioc_update")`. Running the `progeny`function will return also pathway scores for the 3 new pathways
ii) In case you are only interested in the raw model matrix, you can access it [here](https://github.com/saezlab/ConservedFootprints/blob/master/data/progeny_benchmark/models/progeny_matrix_human_v1.csv).

Cheers,
Christian

**Comment by imkeller** [comment]
Thank you, this works well!
