### ISSUE TITLE
Missing Androgen, Estrogen and WNT?

### ISSUE THREAD

**Issue by yesitsjess** [saezlab/progeny#11]
Androgen, Estrogen and WNT are missing from my results?

I only have EGFR Hypoxia JAK.STAT MAPK NFkB PI3K TGFb TNFa Trail VEGF p53

Version 1.8.0 which I installed using bioconductor yesterday

**Comment by imkeller** [comment]
https://github.com/saezlab/progeny/issues/10
I had the same question

**Comment by yesitsjess** [comment]
Ok my mistake, I think I need to use https://github.com/saezlab/ConservedFootprints instead! Sorry!
