### ISSUE TITLE
How to use ConservedFootprints model with PROGENy wrapper

### ISSUE THREAD

**Issue by yesitsjess** [saezlab/progeny#12]
I've found the updated model with Androgen, Estrogen and WNT pathways but how can I use it with the progeny call ("Calculate PROGENy pathway scores from gene expression")? 

[progeny_matrix_human_v1.csv](https://github.com/saezlab/ConservedFootprints/blob/master/data/progeny_benchmark/models/progeny_matrix_human_v1.csv)

**Comment by alberto-valdeolivas** [comment]
Hello, 

The new version of Progeny with the new pathways will be available soon.

**Comment by alberto-valdeolivas** [comment]
Hello, the new version in this repository already contains the 14 pathways. It will also be soon available in Bioconductor.
