### ISSUE TITLE
Error in t(expr[common_genes, , drop = FALSE]) %*% model[common_genes,  :    requires numeric/complex matrix/vector arguments

### ISSUE THREAD

**Issue by yesitsjess** [saezlab/progeny#13]
Following your most simple example and getting an error:

```
# load the downloaded files
gene_table <- readr::read_tsv("Cell_line_RMA_proc_basalExp.txt")

# we need genes in rows and samples in columns
gene_expr <- data.matrix(gene_table[,3:ncol(gene_table)])
colnames(gene_expr) <- sub("DATA.", "", colnames(gene_expr), fixed=TRUE)
rownames(gene_expr) <- gene_table$GENE_SYMBOLS

library(progeny)
pathways <- progeny(gene_expr)

Error in t(expr[common_genes, , drop = FALSE]) %*% model[common_genes,  : 
  requires numeric/complex matrix/vector arguments
```

**Comment by christianholland** [comment]
Hi @yesitsjess,

without having access to your `gene_table` it is hard to trace back the error. However, based on the error message it seems that you have "non-numeric" entries in your matrix. Maybe you have some characters/strings in your `gene_table`?

Cheers,
Christian

**Comment by yesitsjess** [comment]
The gene table is from https://bioconductor.org/packages/release/bioc/vignettes/progeny/inst/doc/progeny.html but I will double check it now to ensure all numeric

**Comment by alberto-valdeolivas** [comment]
Hello @yesitsjess,

Did you solve this issue?

**Comment by nirajkhe** [comment]
Hi @alberto-valdeolivas  and @christianholland,

I am getting the same error as @yesitsjess. 

a <- progeny(input_human)
Error in t(expr[common_genes, , drop = FALSE]) %*% model[common_genes,  : 
  requires numeric/complex matrix/vector arguments

my input file is same as sample input provided input_human 
[input_human.RData.zip](https://github.com/saezlab/progeny/files/5371679/input_human.RData.zip)

Please help me out.

**Comment by yesitsjess** [comment]
I don't actually remember the issue now because it's been so long, but I think this worked for me, hope it's helpful:
```
gene_table = readr::read_tsv("Cell_line_RMA_proc_basalExp.txt")
gene_expr = data.matrix(gene_table[,3:ncol(gene_table)])
colnames(gene_expr) = sub("DATA.", "", colnames(gene_expr), fixed=TRUE)
rownames(gene_expr) = gene_table$GENE_SYMBOLS

library(progeny)
pathways = progeny(gene_expr)
```
