### ISSUE TITLE
Buggy row names after permutation approach

### ISSUE THREAD

**Issue by christianholland** [saezlab/progeny#19]
After running progeny with perm = 1000 there are buggy row names in the output (see below). Probably an artefact from @adugourd initial permutation code
![image](https://user-images.githubusercontent.com/28303875/90402588-fa2e9480-e09f-11ea-85ac-112e98321efd.jpeg)

**Comment by alberto-valdeolivas** [comment]
Yeah, not very nice row name. I will take a look asap. Btw, I do not get notification of the issues...I have to check that.

**Comment by christianholland** [comment]
I think you have to watch repo to get notifications

**Comment by alberto-valdeolivas** [comment]
Yeah, I am not used to check the repo, since for Omnipath we get a notification in the slack channel...

**Comment by alberto-valdeolivas** [comment]
Solved! It should now take the name from your input data frame.
