### ISSUE TITLE
progeny pathway score result differences with number of samples!

### ISSUE THREAD

**Issue by pswaminath** [saezlab/progeny#20]
Hi,
I ran progeny with three different expression matrices. First one with one sample, second with two samples and third  with 7 samples. 
Please see results below:

<img width="1025" alt="Screen Shot 2020-09-24 at 1 21 20 PM" src="https://user-images.githubusercontent.com/49890361/94186123-e67b0880-fe6b-11ea-8f78-29bbb45f0ef7.png">
<img width="1170" alt="Screen Shot 2020-09-24 at 1 19 24 PM" src="https://user-images.githubusercontent.com/49890361/94186750-b122ea80-fe6c-11ea-8c75-ad2b95d0c60d.png">
<img width="1199" alt="Screen Shot 2020-09-24 at 1 07 41 PM" src="https://user-images.githubusercontent.com/49890361/94186812-c435ba80-fe6c-11ea-89e2-e24b26bbfa39.png">

Could you please help me understand the differences in pathway scores? 

 Sample(geneexpn) has different pathway scores when run separately and with one other sample (geneexpn.1) and with 6 other samples (geneexpn.1......geneexpn.6)?  

Why is this different and what statistical tests are used in each case?

Thank you!
PS

**Comment by alberto-valdeolivas** [comment]
Hello,

Thanks for your interest in progeny. 

It seems that you are not doing something in a proper way. Please take a detailed look to the website and the vignettes:

[Website](https://saezlab.github.io/progeny/)
[Vignette](https://saezlab.github.io/progeny/articles/progenyBulk.html)

I ran the example presented in the vignette for the expression matrices taking different numbre of samples and I always get the same results, as expected: 

```
`library(progeny)
library(airway)
library(DESeq2)
data(airway)

# import data to DESeq2 and variance stabilize
dset = DESeqDataSetFromMatrix(assay(airway),
                              colData=as.data.frame(colData(airway)), design=~dex)
dset = estimateSizeFactors(dset)
dset = estimateDispersions(dset)
gene_expr = getVarianceStabilizedData(dset)

# annotate matrix with HGNC symbols
library(biomaRt)
mart = useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
genes = getBM(attributes = c("ensembl_gene_id","hgnc_symbol"),
              values=rownames(gene_expr), mart=mart)
matched = match(rownames(gene_expr), genes$ensembl_gene_id)
rownames(gene_expr) = genes$hgnc_symbol[matched]`

```
```
> progeny(gene_expr, scale=FALSE)
           Androgen      EGFR Estrogen  Hypoxia JAK-STAT     MAPK     NFkB      p53      PI3K
SRR1039508 3560.354 102.57921 2378.804 7188.368 6908.119 1498.063 6503.565 4985.321 -3406.171
SRR1039509 3685.067  99.50551 2303.466 7105.068 6719.287 1491.099 6557.901 4827.590 -3399.817
SRR1039512 3542.674  97.23818 2371.004 7090.892 6797.839 1486.131 6595.533 4916.096 -3398.679
SRR1039513 3679.106  83.70157 2296.401 7025.281 6791.537 1496.362 6591.354 4737.011 -3434.462
SRR1039516 3574.811  97.93880 2368.504 7089.881 6726.273 1511.027 6677.999 4916.772 -3385.351
SRR1039517 3650.615 153.21570 2326.948 7410.503 6616.243 1577.772 6729.452 4738.511 -3351.250
SRR1039520 3556.115 107.82050 2391.093 7110.953 6733.022 1522.946 6498.402 4896.906 -3410.761
SRR1039521 3689.666  93.70156 2302.366 7085.071 6710.628 1519.116 6552.628 4725.944 -3442.887
               TGFb     TNFa    Trail      VEGF      WNT
SRR1039508 2934.773 6674.300 179.1710 -261.3138 599.9021
SRR1039509 2970.748 6747.646 182.0690 -237.8929 588.3165
SRR1039512 2969.717 6775.352 181.4560 -272.0142 595.0036
SRR1039513 2962.698 6797.958 184.1653 -240.9486 579.9830
SRR1039516 2955.877 6841.066 172.5934 -222.5169 587.2642
SRR1039517 3025.103 6911.186 171.9570 -206.4556 585.3535
SRR1039520 2961.105 6662.197 183.8961 -247.0707 601.9346
SRR1039521 3002.158 6740.001 184.3475 -257.4522 584.6887
```

```
> progeny(gene_expr[,c(1:2)], scale=FALSE)
           Androgen      EGFR Estrogen  Hypoxia JAK-STAT     MAPK     NFkB      p53      PI3K
SRR1039508 3560.354 102.57921 2378.804 7188.368 6908.119 1498.063 6503.565 4985.321 -3406.171
SRR1039509 3685.067  99.50551 2303.466 7105.068 6719.287 1491.099 6557.901 4827.590 -3399.817
               TGFb     TNFa   Trail      VEGF      WNT
SRR1039508 2934.773 6674.300 179.171 -261.3138 599.9021
SRR1039509 2970.748 6747.646 182.069 -237.8929 588.3165
```

```
> progeny(gene_expr[,c(1:4)], scale=FALSE)
           Androgen      EGFR Estrogen  Hypoxia JAK-STAT     MAPK     NFkB      p53      PI3K
SRR1039508 3560.354 102.57921 2378.804 7188.368 6908.119 1498.063 6503.565 4985.321 -3406.171
SRR1039509 3685.067  99.50551 2303.466 7105.068 6719.287 1491.099 6557.901 4827.590 -3399.817
SRR1039512 3542.674  97.23818 2371.004 7090.892 6797.839 1486.131 6595.533 4916.096 -3398.679
SRR1039513 3679.106  83.70157 2296.401 7025.281 6791.537 1496.362 6591.354 4737.011 -3434.462
               TGFb     TNFa    Trail      VEGF      WNT
SRR1039508 2934.773 6674.300 179.1710 -261.3138 599.9021
SRR1039509 2970.748 6747.646 182.0690 -237.8929 588.3165
SRR1039512 2969.717 6775.352 181.4560 -272.0142 595.0036
SRR1039513 2962.698 6797.958 184.1653 -240.9486 579.9830
```
Best regards,
Alberto.

**Comment by pswaminath** [comment]
Hi,
Thanks for your quick response. I appreciate your explanations. 
I tried running progeny based on your suggestion.

prjustonesample<-progeny(as.matrix(gene_expr_one,scale=FALSE))
prall7samples<-progeny(as.matrix(gene_expr_all,scale=FALSE))

It worked and the results were not different with one vs all 7 samples. Thanks!

How is this different from the one that I ran below?
I ran progeny with different no of samples in expression matrices to get pathway activity scores and parameters as below.

**prall7samples<-progeny(as.matrix(gene_expr_all,scale=TRUE,organism="Human", top = 500, perm = 10000))**

**By running above command with different no of samples, is where I get the differences.**
Screenshots that I provided earlier were the results of the above command.
Please let me know what changes I need to do.

Once I get the variance stabilized normalization expression matrix, **could I directly proceed to get the pathway activity scores (as in vignette - Running progeny to obtain pathway activity scores section)?** 

**My goal is to do pathway analysis (using pathway activity scores; how each of 11/14 pathways are up/down-regulated in different samples?)**

Thanks much!
PS

**Comment by pswaminath** [comment]
Hi,
I have other questions:
1)My dataset consists of human samples. I am using progeny v 1.6. 
When I run progeny, I get pathway activity scores only for 11 pathways. Should I have to install version 1.9.6 to get all 14 pathways or is it only for mouse?

2) Please also let me know the default values set by progeny function for parameters
organism, top and perm(permutations)?

Thanks!
PS
