### ISSUE TITLE
Incapability of handling large matrices.

### ISSUE THREAD

**Issue by enblacar** [saezlab/progeny#24]
Dear progeny developers. 

I am facing a size issue when working with large Seurat objects ( in my case, 27584 rows and 76680 columns). As the call for `progeny::progeny.Seurat()` makes use of `as.matrix()`, it returns the following error:

`"Error in asMethod(object) : Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105"`

This is due to the size of the object, as rows*columns returns a number of integer values above `.Machine$integer.max` (2147483647). 

Is there a possibility to use `Seurat::as.sparse()` or similars instead of `as.matrix()`? If not, how can I solve this issue?

Best,
Enrique

**Comment by vertesy** [comment]
Hello Guys, 

I also hit the same problem. Is there a version I could test?

```r
progeny(combined.obj, scale=FALSE, organism="Human", top=500, perm=1,  return_assay = TRUE)

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
```

Thanks,
Abel
