### ISSUE TITLE
progenyPerm - example is for progeny, not progenyPerm

### ISSUE THREAD

**Issue by AGordonRobertson** [saezlab/progeny#27]
In progeny v1.10.0, in R 4.0.3/RStudio, the help docs example for progenyPerm has this -
gene_expression <- ...
progeny(gene_expression, scale=TRUE, organism="Human", top=100, perm=10000)

Would you please update this to show a progenyPerm example?

**Comment by adugourd** [comment]
Ah thanks for noticing, progenyPerm shouldn't actually be exported as a function anymore, it is actually used internally when a user uses the progeny function with perm parameter >=2.

So if you with to run progeny with permutations to normalise the scores, which you likely should in default scenarios, simply put 1000 or 10000 in the perm parameter.

We will update the package shortly to correct this.

Does this answers your question ?

**Comment by AGordonRobertson** [comment]
Thank you for responding quickly!

I would like to use PROGENy results in a project that has RNAseq data, and am trying to get to the point where I feel I understand scaling and normalization.

I’m using progeny 1.10.0 in R 4.0.3, in RStudio Version 1.3.1073, in macOS 10.15.7.

I’m running the progeny vignette.

If I do not set perm, the progeny command finishes very quickly:
pathways <- progeny(
  gene_expr,
  scale=FALSE
  #perm = 100
  )

But if I ask for ‘perm=100’, I get a duplicate rowname error -

pathways <- progeny(
  gene_expr,
  scale=FALSE,
  perm = 100
)
# Error in `.rowNamesDF<-`(x, value = value) :
#   duplicate 'row.names' are not allowed
# In addition: Warning message:
#   non-unique values when setting 'row.names': ‘’, ‘AADACL2’, ‘AADACL2-AS1’, ‘ABCF1’, ‘ABHD16A’, ‘AGER’, ‘AGK’, ‘AGPAT1’, ‘AIF1’, ‘ANO4’, ‘APOBEC3B-AS1’, ‘APOM’, ‘ATAT1’, ‘ATF6B’, ‘ATP23’, ‘ATP6V1G2’, ‘ATP6V1G3’, ‘B3GALT4’, ‘BAG6’, ‘BRD2’, ‘BTNL2’, ‘C2’, ‘C2-AS1’, ‘C21orf62’, ‘C21orf62-AS1’, ‘C4A’, ‘C4A-AS1’, ‘C4B’, ‘C6orf136’, ‘C6orf15’, ‘C6orf47’, ‘C6orf47-AS1’, ‘CCHCR1’, ‘CDSN’, ‘CES1’, ‘CES5A’, ‘CFB’, ‘CLIC1’, ‘CLK2’, ‘COL11A2’, ‘COL11A2P1’, ‘CSNK2B’, ‘CTSO’, ‘CUTA’, ‘CYP21A1P’, ‘CYP21A2’, ‘CYP2D6’, ‘CYP2D7’, ‘CYP2D8P’, ‘DAXX’, ‘DDAH2’, ‘DDR1’, ‘DDR1-DT’, ‘DDX11L8’, ‘DDX39B’, ‘DDX39B-AS1’, ‘DDX39BP1’, ‘DDX39BP2’, ‘DDX6P1’, ‘DENND11’, ‘DHFRP2’, ‘DHX16’, ‘DNAJC28’, ‘DOC2B’, ‘DSEL’, ‘DUXAP8’, ‘DXO’, ‘EGFL8’, ‘EHMT2’, [... truncated]
# Timing stopped at: 0.271 0.009 0.28

Checking the rownames of gene_expr, I find many duplicated rownames -
rev(sort(table(rownames(gene_expr))))[1:10]
#         ZNRD1ASP      ZFP57      UBDP1       TUBB      TSBP1     TRIM40 TRIM31-AS1     TRIM31     TRIM26
# 15614          8          8          8          8          8          8          8          8          8

To check whether this is repeatable, I closed and restarted RStudio, and walked down through the vignette again. The error is repeatable.

Could I ask that you check whether you also get this error?

Gordon


On Dec 14, 2020, at 00:57, Aurelien Dugourd <notifications@github.com<mailto:notifications@github.com>> wrote:



Ah thanks for noticing, progenyPerm shouldn't actually be exported as a function anymore, it is actually used internally when a user uses the progeny function with perm parameter >=2.

So if you with to run progeny with permutations to normalise the scores, which you likely should in default scenarios, simply put 1000 or 10000 in the perm parameter.

We will update the package shortly to correct this.

Does this answers your question ?

**Comment by AGordonRobertson** [comment]
I would like to use PROGENy, but would prefer that perm be fixed, if it's actually not working. Could I ask what timeline you see for checking perm, and fixing it, if it's not working? Thanks -

**Comment by alberto-valdeolivas** [comment]
Hello, 

You should not have duplicated rownames in your input matrix for Progeny. This means that you have duplicated genes. You have to figure out what to do with these duplicated genes (like computing their average expression) before running Progeny with or without Permutations. Otherwise, these duplicated genes may contribute twice to Progeny pathway activity scores.

ProgenyPermutations does not need to be fixed in that sense. Indeed, we need to control in Progeny without permutations that no duplicated genes are provided as input. 

Best regards,
Alberto.

**Comment by AGordonRobertson** [comment]
If I follow the vignette code, I get many duplicated rownames in gene_expr. 
...
# annotate matrix with HGNC symbols
library(biomaRt)
mart = useDataset("hsapiens_gene_ensembl", useMart("ensembl"))
genes = getBM(attributes = c("ensembl_gene_id","hgnc_symbol"),
              values=rownames(gene_expr), mart=mart)
matched = match(rownames(gene_expr), genes$ensembl_gene_id)
rownames(gene_expr) = genes$hgnc_symbol[matched]

#-- check unique rownames()
rev(sort(table(rownames(gene_expr))))[1:10]
#         ZNRD1ASP      ZFP57      UBDP1       TUBB      TSBP1     TRIM40 TRIM31-AS1     TRIM31     TRIM26 
# 15614          8          8          8          8          8          8          8          8          8 

What's somewhat surprising is that I can run this gene_expr in progeny if I do **not** use 'perm' -
library(progeny)
pathways <- progeny(
  gene_expr, 
  scale=FALSE
)
...but if I try to set 'perm' I get a duplicated rownames error. 
pathways <- progeny(
  gene_expr, 
  scale=FALSE,
  perm = 100
)
Error in `.rowNamesDF<-`(x, value = value) : 
  duplicate 'row.names' are not allowed
...

If I leave the vignette and run progeny on a data frame that has FPKMs for ~19k coding genes and ~80 tumour samples, ensuring that rownames are unique, I can set perm, or not. E.g.
pathways <- progeny(
  as.matrix(fpkm.df), 
  scale=FALSE, 
  perm = 10000,
  top = 200
)

The above suggests that there's a problem with the vignette, as gene_exp has duplicated rownames. Should progeny run when 'perm' is not set but there's duplicated rownames?

Thanks -

**Comment by alberto-valdeolivas** [comment]
when running Progeny one can call to two different functions:

1. If the parameter `perm = 1` (value by default), we run a function where the duplicated rownames (gene names) are not controlled. This is the case in the vignette. That's why I mentioned before that we should modify this function to control taht and prevent having duplicated gene names in the input matrix. Once this modification is done, we will need to do something in the vignette with the expression matrix to avoid having duplicated gene names (For instance, computing their average expression as mentioned before). 
2. If the parameter `perm > 1 `, we run a function where the duplicated rownames are controlled. 
 
I hope this clarifies the issue. 

Best,
Alberto.
