### ISSUE TITLE
gene weights and directions

### ISSUE THREAD

**Issue by Semple-bio** [saezlab/progeny#29]
Good day.
When I was browsing the model in the model_*_full.rda files, I found the following:
The 2 topmost p-value genes in the MAPK pathway are Dusp6 and Spry4, both are inhibitors/negative regulators of the MAPK pathway, and they have high, positive weights. On the other hand in the p53 pathway most top hits are direct p53 target genes, also with positive weights.
I'm wondering that can't this distort the 'activity' of the MAPK pathway if negative regulators have such high positive weights?

**Comment by bence-szalai** [comment]
Hi @Sample-bio, 

it is a very common in case of gene expression regulation, that activation of pathway X stimulates expression of gene Y, and the protein product of gene Y inhibits pathway X.  It is some form of negative feedback mechanisms. In the case of MAPK pathway, active MAPK stimulates the expression of DUSPs (via some transcription factors), and DUSP proteins act as negative feedback, inhibiting the activity of MAPK pathway. So it is not distorting the results of PROGENy, but recapitulates a known biological mechanism.

It is important, that PROGENy uses the gene expression as a "footprint" of pathway activity. That means that we are inferring the activity of a pathway from the expression of pathway regulated genes, not from the expression of pathway member genes. Several bioinformatic methods use the expression of pathway member genes to infer pathway activity (in this case high expression of DUSPs would considered as inactive MAPK pathway, as your question suggests), however, as shown in the original PROGENy paper, PROGENy generally performs better than these methods. If you are interested in the differences between "footprint" based and "membership" based pathway analysis techniques, I can suggest one recent paper of us: https://febs.onlinelibrary.wiley.com/doi/10.1002/1873-3468.14011 

BTW in case of p53, there is also present these negative feedback: p53 increases the expression of MDM2 (high positive weight in PROGENy matrix), which is the main inhibitor of TP53.

Hope this helps, 

Bence
