### ISSUE TITLE
Input Data Requirements Not Specified by Vignette

### ISSUE THREAD

**Issue by DarioS** [saezlab/progeny#30]
The vignette immediately launches into an analysis but I would like to see some explanation of RNA-seq abundance summaries. Should counts, FPKM, TPM or something else be provided? What should definitely not be input by the user? What if the user already has an edgeR pipeline? I see the example uses DESeq2 but it's unclear what other units of measurement are valid to use. Also, Section 1 has a link to bioRxiv but it could be updated to refer to _Nature Communications_ instead. log-scale microarray values and log-scale RNA-seq counts are quite different numbers in scale. How can the same model work for both?

**Comment by adugourd** [comment]
to compute the scores, Progeny does a matrix multiplication between the progeny weight matrix and the users input statistics. The progeny weights were estimated from linear model parameters trained on differential z-scores between pertubations and control experiments. The scores are then normalised using a gene permutation approach.

Thus, as for regular gene set enrichment approaches, any differential statistic (t-value, foldchange, etc...) is supposed to work. However, the score interpretation will depend on the input statistic. 

In the same manner, when running progeny directly on a count or micro-array matrix, as long as the values are normalised to follow more or less a bell shaped distribution, the model should work.

It is however up to the users discretion to interpret the value of a given pathway score in the light of knowing that this score represent a normalised weighted mean (where weights are the progeny matrix weights) of the input statistic.

**Comment by DarioS** [comment]
I wonder if you are aware of:

- [Transcript Length Bias in RNA-seq Data Confounds Systems Biology](https://biologydirect.biomedcentral.com/articles/10.1186/1745-6150-4-14) (2009) _Biology Direct_ 
- [Gene Ontology Analysis for RNA-seq: Accounting for Selection Bias](https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-2-r14) (2010) _Genome Biology_

Genes which are longer will have systematically higher counts becase the read length is constant. I don't think that the instructions are suitable for RNA-seq. Counts should be advised against in favour of F.P.K.M. or T.P.M. which adjust for gene length.

**Comment by adugourd** [comment]
Thank you for pointing this out. This is indeed something we had to consider. This biais can be a problem when pathway scores are interpreted as they are in a single sample. We will make this clearer.

**Comment by messersc** [comment]
Hi all,

Also see https://github.com/saezlab/progeny/issues/7 for a discussion I had with Michael a while back on this. I would also lean towards normalizing by gene length, or do both and have a look if results are consistent. 

Kind regards,
Clemens

**Comment by DarioS** [comment]
Thanks for alerting me to your identical question a couple of years ago. This important detail should be discussed in the vignette.

**Comment by AGordonRobertson** [comment]
For a TCGA cohort, I've recently compared PROGENy results for RSEM_normalized, log2(RSEM_normalized), and 10^6*RSEM_scaled_estimate, which I understand is TPM. It would be helpful to have some guidance in the vignette on different inputs, and on how to think about pathway activities that are returned as positive, vs. negative.
