### ISSUE TITLE
Issue when Importing progeny for another package

### ISSUE THREAD

**Issue by federicomarini** [saezlab/progeny#31]
Hi,
we're working on another package where we import the functionality of `progeny`, and we're handling the dependencies with the usual `Imports` line and statements.
Still, the function call as the required `model_human_full` object is not exported by `progeny` itself, so it would require a call to `library(progeny)`, which is to be avoided if one does not want the note via R CMD check.

Can this `model_human_full` (and while we're at it) data object be directly exported/called explicitly in the `getModel` function? https://github.com/saezlab/progeny/blob/535f5488153d1392846f4f508b5bcdcb6c269fce/R/progenySuppFunc.r#L185

I think that might be enough to solve the issue on our side.
Thanks in advance for looking into it!
Federico

**Comment by alberto-valdeolivas** [comment]
Hello @federicomarini,

Thanks for using Progeny. 

Do you need to use the full data frame of `model_human_full`? I mean, what you get with the `getModel ` function is actually the same but spread into a matrix format and filtered to select the most relevant genes per pathway. It is what we use as input for the progeny main functions. You can increase the number of `top `selected genes to have the full model. 

Are you sure you need to do the `library(progeny)` if you did imported the package? Take a look [here](https://stackoverflow.com/questions/37682268/using-r-package-data-in-function-without-loading-it). I do not know if this is exactly your problem. 

Let me know if this helps.

Best, 
Alberto

**Comment by federicomarini** [comment]
Hi Alberto, 
thanks for the quick response.

We are actually just calling `progeny()`'s main function, so `getModel()` is called in the background.
If we do so without having loaded the full `progeny` package (with the library call), the error pops up when checking the example of the function.

I think it might be related to the fact that the datasets are not fully exported?
Anyway: if you prepend `progeny::` before the `model_*_full` objects, it seems to work as expected. And the other functionality of the package is pretty much unaffected (as expected/hoped).
If you want, I am happy to throw in a micro-PR for that.

**Comment by alberto-valdeolivas** [comment]
Hi again @federicomarini, 

Yeah, I am happy if you can do the micro-PR. This modification should be fine for you and has no impact for us.

Best regards,
Alberto.

**Comment by federicomarini** [comment]
Hi there Alberto, PR's in.
As mentioned in there, it is tested on the current R/Bioc-devel for MacOS.
Thanks for allowing this contribution!

**Comment by alberto-valdeolivas** [comment]
Many thanks! It is done :)

**Comment by federicomarini** [comment]
Awesome, thanks. I thought I'd leave it to you to handle the whole version bump & push upstream to Bioc so that it propagates.
Meanwhile, I'll use it with the local version via `R CMD INSTALL` for the whole checking processes 😉
