### ISSUE TITLE
Bias in 14 pathway collection

### ISSUE THREAD

**Issue by asumann** [saezlab/progeny#33]
Hi,

14 pathways are mostly cancer related as the 2018 paper also focuses on cancer gene expression(Shubert et al. 2018). Can we say this would generate a bias when we look at non-cancer gene expression sets?

I am looking at immunological disease and pathway results from Progeny and transcriptional factor results from Dorothea looks biased to cancer related pathways and TFs. Though, it shouldn't be a problem for Dorothea as I am using Omnipath resources. But how about Progeny?

Is it possible to link progeny-dorothea-carnival pipeline with a larger pathway database?

All the best,
Asuman

**Comment by adugourd** [comment]
Hi,

Indeed,  although it is not really clear to what extent, there is a bias in progeny toward cancer related pathway and signatures.

We are actually looking into extending progeny pathway ressource, but this is a large endeavor that will take time. 

There may also be a bias toward cancer in dorothea, but it should be to a lesser extent. Basically the bias in dorothea shouldn't be larger than the overall bias toward cancer you can find in any molecular interaction resources out there.

**Comment by asumann** [comment]
Thank you @adugourd! I have dug the bias reseach. This [paper](https://www.frontiersin.org/articles/10.3389/fgene.2015.00260/full) could be helpful for people to understand study bias.
