### ISSUE TITLE
Exporting scatter plot to see full list of genes associated with pathways

### ISSUE THREAD

**Issue by Vernonjustice** [saezlab/progeny#34]
I did I need help exporting the scatter plot derived after running this  following code;

 

```{r ProgenySccater_1, message=FALSE, warning=FALSE}

prog_matrix <- getModel("Human", top=100) %>%

    as.data.frame()  %>%

    tibble::rownames_to_column("GeneID")

 

ttop_ETS1vsEV_df <- ttop_ETS1vsEV_matrix %>%

    as.data.frame() %>%

    tibble::rownames_to_column("GeneID")

 

scat_plots <- progeny::progenyScatter(df = ttop_ETS1vsEV_df,

    weight_matrix = prog_matrix,

    statName = "t_values", verbose = FALSE)

```

 

```{r ProgenySccater_2, dpi=300}

plot(scat_plots[[1]]$`MAPK`)

```

 

When I plot the scatter plot, I see the graph for an assigned pathway such as MAPK or TNFa. Is there is a way to export the scat_plot file as csv so that I can see the full list of genes associated with each pathway?

**Comment by adugourd** [comment]
Hi,

Yes. it is possible. However there is no implemented function to do that automatically. 

You can very easily see which are the responsive gene of each pathway by looking into the model_human_full variable that should be in your global environment after you load the progeny library.

Cheers

Aurelien
