### ISSUE TITLE
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c,

### ISSUE THREAD

**Issue by xyn0813** [saezlab/progeny#35]
I tried to use progeny to analyze  about 70 thousands cells and I got the error

Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
Calls: progeny ... progeny -> as.matrix -> as.matrix.Matrix -> as -> asMethod
Execution halted

how to fix it ?

**Comment by adugourd** [comment]
Hi,

These are too many cells for a single run. You can try to split your dataset in chunks of 500 cells and run them one at a time.

Cheers,

Aurelien
