### ISSUE TITLE
how to apply progeny on differential expression analysis result?

### ISSUE THREAD

**Issue by shengqh** [saezlab/progeny#40]
Based on paper "Robustness and applicability of transcription factor and pathway analysis tools on single-cell RNA-seq data", progeny can be used for pathway analysis instead of GSEA. However, the progeny example shows how to use single cell gene matrix rather than differential expression analysis result. Would you please provide an example that how to use progeny based on differential expression analysis result (gene symbol with pvalue and fold change)? Thank you so much.

**Comment by mschubert** [comment]
Hi @shengqh,

Progeny does not work on differential expression results. Instead, you can score each of your samples and then test for a difference in pathway scores.

Does that help?

**Comment by adugourd** [comment]
You can check the transcriptutorial that shows how to use progeny downstream of a differential analysis result: https://github.com/saezlab/transcriptutorial
