### ISSUE TITLE
NES for each pathway

### ISSUE THREAD

**Issue by HocheolJang426** [saezlab/progeny#41]
Hi
I'm using PROGENy recently
It is really power tool to deciphering RNA World

Recently I read vignette, https://github.com/saezlab/transcriptutorial/blob/master/scripts/03_Pathway_activity_with_Progeny.md
I'm wondering I can get NES from seurat, not matrix 
In this vignette, NES calculated from limma-calculated matrix.
But I want to calculate NES from seurat

I followed this tutorial, https://saezlab.github.io/progeny/articles/ProgenySingleCell.html
Is there any way to calculate NES from seurat, followed by this tutorial?

Thanks

**Comment by adugourd** [comment]
Hi,

thanks for your interest in the tool :)

Basically, the simplest way to do it is to first pseudo-bulk your data at the level of the cell population you defined. Then you can run differential analysis on with the pseudobulk data and use the resulting t-values as input for decoupler. Here is an example in python: https://decoupler-py.readthedocs.io/en/latest/notebooks/pseudobulk.html

Cheers
