### ISSUE TITLE
Return Gene List from progenyScatter

### ISSUE THREAD

**Issue by HocheolJang426** [saezlab/progeny#45]
Hi

I'm really enjoying your wonderful package, progeny

In pathway enrichment analysis and following progenyScatter, I can plot genes according to pathway.
I show the result of my analysis below;
![image](https://user-images.githubusercontent.com/70268227/163526350-382d6528-f4d0-460a-8758-4f2cbec9d876.png)
I'm wondering I can get the list of gene names shown on figure
In this analysis, ISG15, MX1, IFI44L...
I checked the arguments that consist progenyScatter, I can't find any gene names
How can I return gene names from progenyScatter and each pathway?

**Comment by adugourd** [comment]
Hi,

thanks for your interest in the tool :)

You can find those genes in the weight matrix of progeny. You can get the weight matrix by using the function progeny::getModel()

Cheers,

Aurelien
