### ISSUE TITLE
Whether progeny could be used on gene-chip data

### ISSUE THREAD

**Issue by Caary** [saezlab/progeny#46]
Hi
I'm using PROGENy recently
It is a really powerful tool for deciphering pathway activity from bulk and single-cell data.

I am a little confused that whether this package could be used on gene-chip data for inferring pathway activity.

Thanks

**Comment by adugourd** [comment]
Hi,

thanks for your interest in the tool !
I wouldn't advise to use it with gene/chip data though.

Cheers,

Aurelien

**Comment by Caary** [comment]
> 

Thanks, Aurelien.
 
That means the expression matrix of the progeny input should be from RNA-Seq or ScRNA-Seq, which from microarray may not be appropriate.

Best,
Li

**Comment by adugourd** [comment]
Ah sorry, When i read gene/chip I thought you meant chip-seq data data. 

Microarray data is good as an input :) But it should be normalised and log2 transformed.

**Comment by Caary** [comment]
> 
Thanks, Aurelien.
Sorry for did not make it clear at the first time.

Best,
Li
