### ISSUE TITLE
Web page deployment faulty?

### ISSUE THREAD

**Issue by mschubert** [saezlab/progeny#51]
Hi,

I just checked the web page at https://saezlab.github.io/progeny/ and it looked like this:

![image](https://user-images.githubusercontent.com/442360/215335286-fcbb4330-fc52-4883-afdf-db23e3bcbeef.png)

Was there maybe something going wrong with the `pkgdown` deployment? Maybe also just missing a merge of https://github.com/saezlab/progeny/pull/49?

**Comment by deeenes** [comment]
This is now fixed, thanks @mschubert for reporting!
