### ISSUE TITLE
p53 pathway target MDM2 weighting

### ISSUE THREAD

**Issue by ojziff** [saezlab/progeny#52]
Dear PROGENy team,

I am interested in the p53 pathway and have noted that the target MDM2 has a weight of +8.19. However, MDM2 is a well-established [negative regulator](https://en.wikipedia.org/wiki/Mdm2) of the p53 pathway. Please could you explain why MDM2 has a positive weighting if it is a negative regulator? Could it be because p53 activations increases MDM2 in a [negative feedback loop](https://www.pnas.org/doi/10.1073/pnas.210171597#F1)? 

Many thanks,
Oliver

**Comment by bence-szalai** [comment]
Hi @ojziff ,

You are right that MDM2 **protein** is a negative regulator of TP53. However, PROGENy is footprint based method, which means that it does not calculate pathway activity from the expression of pathway member genes, but from the expression of pathway regulated genes (this concept is explained more detailed in the [PROGENy paper](https://www.nature.com/articles/s41467-017-02391-6), and also some other related papers [paper1]( https://www.sciencedirect.com/science/article/pii/S2452310019300149) and [paper2](https://febs.onlinelibrary.wiley.com/doi/full/10.1002/1873-3468.14011)). Also, [MDM2 gene expression is induced by p53](https://pubmed.ncbi.nlm.nih.gov/8440237/) - probably as part of some negative feedback mechanism as you also wrote. So from the perspective of PROGENy, using a large positive weight for MDM2 makes sense (high MDM2 expression suggests high p53 pathway activity, as MDM2 expression is induced by p53 pathway). Based on the benchmarks in the PROGENy paper (eg.: Figure3), this looks like a working assumption (PROGENy correctly predicts a decreased p53 activity in TP53 mutant cell lines). Also, you can check the file below (created on [DepMap](https://depmap.org/portal/), that MDM2 expression is higher in cancer cell lines, where TP53 is not mutated (i.e. TP53 is active), also suggesting that increased MDM2 expression is a sign of active p53.
![newplot](https://user-images.githubusercontent.com/8297128/216846171-614da9b8-c692-432e-b9c2-82cf104f0428.png)

Hope it makes sense,

Bence

**Comment by ojziff** [comment]
Very helpful thanks!
