### ISSUE TITLE
Which seurat assay to use for progeny

### ISSUE THREAD

**Issue by cf98** [saezlab/progeny#53]
Hi PROGENy authors,

Thanks for developing this great tool.

I found in [this tutorial](https://saezlab.github.io/progeny/articles/ProgenySingleCell.html) that it uses NormalizeData() and ScaleData() before running PROGENy.

Is it ok to use assay SCT, or would you suggest using the way in the tutorial?

Thanks!

**Comment by PauBadiaM** [comment]
Hi @cf98 

Thanks for using it! You can use the SCT assay. If you check our updated vignette in decoupleR (a unified framework of our resources in the lab) you can see that as an example we use the classic normalized counts and then we scale the obtained activities afterwards, here's the link to it: https://saezlab.github.io/decoupleR/articles/pw_sc.html
Hope this is helpful.

**Comment by cf98** [comment]
Thank you! Can I ask another question. Does decoupleR uses the log normalized data slot, or the scale.data slot? Should I Run ScaleData() for my Seurat object if I want to get progeny results?

Thanks!

**Comment by PauBadiaM** [comment]
Hi @cf98 

You can use the log normalized data slot or the SCT assay, infer activities and then scale them (as shown in the vignette). Alternatively, you can pass the scale.data slot directly and infer activities from it.
