### ISSUE TITLE
Does the proteomics data can also use this tool to get the prediction of the pathway activity?

### ISSUE THREAD

**Issue by polarbearsmall** [saezlab/progeny#54]
Dear Authors, 

Thanks a lot for the amazing great tools!

May I have your guidance that if the progeny can be used to process the proteomics data? 

Say the proteomics data have covert the protein/peptide accession to the gene symbol. If suitable, how to normalize/transform the original abundance value, TPM...? As the proteomics data are much less items than the gene items in the RNAseq. 

Thank you very much! Best!

**Comment by adugourd** [comment]
Hi,

Sadly, using progeny with proteomic data is really not advised. The progeny signatures where build using RNA datasets, and our internal testing have shown that progeny scores estimated with proteomic data where not very reliable.

Cheers,

Aurelien

**Comment by polarbearsmall** [comment]
Thanks a lot for your guidance!

May I know if you can guide several tools that can infer the pathway's activity for the proteomics data? decoupleR? 

All the best!
