### ISSUE TITLE
p-value for progeny on scRNA-seq clusters

### ISSUE THREAD

**Issue by frisalonza** [saezlab/progeny#55]
Hello!
I used progeny on a cluster of a scRNA-seq dataset for inferring pathways activity in two different conditions. I followed this tutorial:
https://saezlab.github.io/progeny/articles/ProgenySingleCell.html. I would like to have a p-value for each pathway, but I can only see the progeny score. Is it present somewhere? 
Alternatively, I see that in this case it is calculated an average and a standard deviation of the pathways for each cluster, should I take these values and perform a statistics by myself? If yes, what type of test would you suggest?

Thank you!

**Comment by adugourd** [comment]
thanks for your interest ! 

For single cell data, I owuld recommend to follow our most up to date tutorial to use progeny, that oyu can find here: https://decoupler-py.readthedocs.io/en/latest/notebooks/progeny.html

Cheers,

Aurelien
