### ISSUE TITLE
scatter plot adjustment

### ISSUE THREAD

**Issue by whiteorchid** [saezlab/progeny#56]
Dear Authors,

Thanks a lot for your great software of progeny! 

May I apply for your guidance on the scatter plot?

1) Is there a way to modify the plots, say, add arrows to the dot to the gene
2) For the density plot, it seems not always reflect the difference between different pathways
3) For the dots for a pathway, is it necessary to label all the dots, or if there is a threshold to only labels the top10 genes

Thank you very much for your guidance!

![testttt](https://github.com/saezlab/progeny/assets/6839620/12453091-0d1e-4856-9b2e-e971da8184c0)

**Comment by adugourd** [comment]
Hi,

1) sorry, this is something that has to do with the ggrepel package, I haven't tried to look into this myself.
2) the density plot represent the distributuion of all the tested genes (all the genes that are in your input dataframe, not just the ones that are relevant for the given patway). Thus it should be the same for each pathway scatter plot.
3)WE haven't included such threshold, but it should be doable :) you are welcome to fork this 

Finally, I would say that you probably want to use decoupleR in the futur to run progeny. You can check the tutorial and doc of the package to run progeny analysis with deocupleR, which has more up-to-date functions: https://saezlab.github.io/decoupleR/articles/pw_bk.html
Cheers,

Aurelien

**Comment by whiteorchid** [comment]
Thanks a lot for your kind guidance! 

Yeah, ggrepel should be able to do the arrows. Now have a better understanding of the density plot and the threshold.

Thank you very much for your kind guidance!

Best,
