### ISSUE TITLE
Leaving out androgen pathway in tutorial?

### ISSUE THREAD

**Issue by CB-postech** [saezlab/progeny#58]
In your [PROGENy tutorial using R](https://saezlab.github.io/progeny/articles/ProgenySingleCell.html), I've noticed that you have left out the androgen pathway when handling data with the script below.
```
progeny_hmap = pheatmap(t(summarized_progeny_scores_df[,-1]),fontsize=14, 
                        fontsize_row = 10, 
                        color=myColor, breaks = progenyBreaks, 
                        main = "PROGENy (500)", angle_col = 45,
                        treeheight_col = 0,  border_color = NA)
```
The androgen pathway, probably because it's the first pathway when sorted alphabetically, is removed due to the [, -1] selection in the first line of the script above.

Is this a simple mistake, or is their a specific reason for this?

**Comment by adugourd** [comment]
sorry for delay, likelly a simple mistake indeed.
