### ISSUE TITLE
Layer counts isn't present in the assay object; returning NULL

### ISSUE THREAD

**Issue by Noralii** [saezlab/progeny#59]
data_Endo <- progeny(data_Endo, scale=FALSE, organism="Mouse", top=500, perm=1, 
                    return_assay = TRUE)
Warning: Layer counts isn't present in the assay object; returning NULL

**Comment by adugourd** [comment]
This is likely an outdated use case.

Please see: https://decoupler-py.readthedocs.io/en/latest/notebooks/bulk.html#PROGENy-model for latest tutorial and up to date
