### ISSUE TITLE
Gene symbols used by PROGENY

### ISSUE THREAD

**Issue by taraurselmann** [saezlab/progeny#60]
Hello,

Thank you for making this package, it has provided me with a lot of insight into my data!
 
I was looking into a PROGENy table (model_human_full), which contains a pathway score for every pathway per gene. The PROGENy function indicates that official HGNC symbols should be used. However, when I was looking at that table I saw that some genes are not the official HGNC symbol anymore, for example: 
KIAA1429 is now known as VIRMA
HIST4H4 is now known as H4C16 (this is an issue for all other histone genes too)

I’ve noticed that when I use a data set containing older or new symbols, they provide different pathway scores because of their differences in gene names.

I was wondering if this is a known issue, or if I could easily resolve this for future use.
Thank you in advance!

**Comment by adugourd** [comment]
thanks for pointing this out. The gene symboles have not been updated in a while in the model actually. We will try to solve it for the futur :)

**Comment by taraurselmann** [comment]
Thank you, that is very helpful!  :)
