### ISSUE TITLE
SPIA-modified z-scores to add information about position of gene in pathway

### ISSUE THREAD

**Issue by jadeshi** [saezlab/progeny#8]
Hey, I came across PROGENy after reading about another pathway mapping technique SPIA that is also referenced in your paper, and I was wondering if there would be value to combining elements from both techniques. Specifically, I'm thinking about the following:

Take the current z-score matrix, and for each pathway, modify the scores of all on-pathway genes using a relationship like Eq (1) from the original SPIA paper by Tarca et al, where you treat the current z-scores as the expression differences:

https://www.ncbi.nlm.nih.gov/pubmed/18990722

This will create a modified matrix of z-scores that will take into account the location of the genes in the pathway, and allow upstream genes to "contribute their z-score" to their downstream neighbors. The off-pathway genes can be left alone. 

Would this be something that you think would be worth adding? I'm fairly new to this field so please excuse me if this is a dumb suggestion!

**Comment by mschubert** [comment]
Maybe I'm missing something, but I think this will not work.

SPIA relies on a known pathway graph (the "interactions" between genes in eqn. 1) and the expression differences of its components (they call them perturbations here; but these are changes from the mean, not actual perturbations). In constrast, our genes are downstream of an experimental perturbation and do not have a known interaction structure.
