### ISSUE TITLE
use with single gene list and scores

### ISSUE THREAD

**Issue by bedward1** [saezlab/progeny#9]
Hi
I have a single list of genes and scores created by a meta analysis between control and test samples.  Would it be possible to use progeny with this data? Or must it require a control and test separately?
Thanks
Bryan

**Comment by mschubert** [comment]
Hi Bryan,

This is a bit different from what this package is intending to do. There are still options (which is best depends on your data, maybe you can elaborate a bit on that):

**Using a single list**

If your list contains few genes, the easiest way I see would be to check for a significant overlap between the progeny top 100 genes for a given pathway and your list using a Fisher's Exact Test.

If you have a lot of genes, you could use Gene Set Enrichment Analysis to see whether the progeny top 100 cluster towards the top or the bottom of your ranked list.

Alternatively, you could devise your own permutation test based on cosine similarity between your weighted list and the progeny coefficients.

**If you can get a list per sample**

You could apply progeny to both your control and your test samples, and then use a simple parametric test (e.g. t-test) to test for differences between them.

Hope that helps!
Michael

**Comment by bedward1** [comment]
Hi Michael
Thanks a lot for the response.  The data i have is basically in limma
toptable output, with all genes in the test and log2FC and p-value.
It sounds as if GSEA might be the best approach.
Thanks
Bryan
